@startuml test
class MyClass{
    int cringe
    list merCringe
    metodse()
}

class MySecondClass{
    int cringe2
    list merCringe2
    metode2()
}

MySecondClass ---> MyClass : is played on >
@enduml