@startuml 3
class Trener{
    spesialisering : str
    lag : list[Lag]
}
class Lag{
    medlemmer : list[Spiller | Trener]
}

class Klubb{
    lag : list[Lag]
    spillere : list[Spiller]
    trenere : list[Trener]
}

class Spiller{
    posisjon : str
    lag : str
}

Lag "1" -up-* "many" Klubb
Lag "many" *-left- "many" Trener
Lag "many" *-right- "1" Spiller
Trener "1" -up-* "many" Klubb
Spiller "1" -up-* "many" Klubb

@enduml