@startuml 4
class Bok{
    +forfatter : list[Forfatter]
    +forlag : str
    +ISBNnummer : int
    +tittel : str
    +utgivelsesår : int
    +baksidetekst : str
}
class Bokhandel{
    +bokassortement : list[Bok]
    +registrerBok(bok:Bok)
}
class Forfatter{
    +skrevne_bøker : list[Bok]
}   
class Fagbok{
    +fagområde : str
}
class Skjønnlitteratur{
    +sjanger : str
}

Fagbok -up-|> Bok
Skjønnlitteratur -up-|> Bok
Forfatter "1,2,..." -left-* "*" Bok
Bok "many" -up-* "many" Bokhandel: registrerBok(Bok) >

@enduml