@startuml Argsflix
class App{
    favoritter : Bucketlist
    legg_til_bucketlist(index|title)
    søk() -> Søkeresultat
}
class VisuellMedia{
    title : str
    år : int
    imdb_id : str
    poster : str
    sett : bool
}

class Film{
    lengde : int
    DVD : str
}

class Serie{
    antall_sesonger : int
}
class Bucketlist{
    #media : list[VisuellMedia]
    +legg_til()
}

class Søkeresultat{
    title : str
    år : int
    imdb_id : str
    poster : str
    type : str
}

class Søk{
    film_liste : list[Søkeresultat]
    søk_title()
    søk_id()
}

VisuellMedia <|-down- Film
VisuellMedia <|-down- Serie
Bucketlist "any" *-up- Film
Bucketlist "any" *-up- Serie
App "1" *-up- Søk
Søk "any" *-up- Søkeresultat
App "1" *-right- Bucketlist
@enduml